// Mocks generated by Mockito 5.4.4 from annotations
// in doctoroncall/test/widget/profile_screen_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:dio/dio.dart' as _i3;
import 'package:doctoroncall/core/network/api_client.dart' as _i8;
import 'package:doctoroncall/core/services/biometric_service.dart' as _i11;
import 'package:doctoroncall/features/auth/data/models/user_model.dart' as _i2;
import 'package:doctoroncall/features/auth/domain/repositories/auth_repository.dart'
    as _i6;
import 'package:doctoroncall/features/messages/data/datasources/chat_remote_data_source.dart'
    as _i9;
import 'package:doctoroncall/features/messages/data/models/chat_contact_model.dart'
    as _i10;
import 'package:doctoroncall/features/messages/data/models/message_model.dart'
    as _i5;
import 'package:flutter/services.dart' as _i13;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i4;
import 'package:local_auth/local_auth.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserModel_0 extends _i1.SmartFake implements _i2.UserModel {
  _FakeUserModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDio_1 extends _i1.SmartFake implements _i3.Dio {
  _FakeDio_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlutterSecureStorage_2 extends _i1.SmartFake
    implements _i4.FlutterSecureStorage {
  _FakeFlutterSecureStorage_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMessageModel_3 extends _i1.SmartFake implements _i5.MessageModel {
  _FakeMessageModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIOSOptions_4 extends _i1.SmartFake implements _i4.IOSOptions {
  _FakeIOSOptions_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAndroidOptions_5 extends _i1.SmartFake
    implements _i4.AndroidOptions {
  _FakeAndroidOptions_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLinuxOptions_6 extends _i1.SmartFake implements _i4.LinuxOptions {
  _FakeLinuxOptions_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWindowsOptions_7 extends _i1.SmartFake
    implements _i4.WindowsOptions {
  _FakeWindowsOptions_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWebOptions_8 extends _i1.SmartFake implements _i4.WebOptions {
  _FakeWebOptions_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMacOsOptions_9 extends _i1.SmartFake implements _i4.MacOsOptions {
  _FakeMacOsOptions_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i6.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> signUp(
    _i2.UserModel? user,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [
            user,
            password,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.UserModel> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i7.Future<_i2.UserModel>.value(_FakeUserModel_0(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i7.Future<_i2.UserModel>);

  @override
  _i7.Future<_i2.UserModel> googleLogin(String? idToken) => (super.noSuchMethod(
        Invocation.method(
          #googleLogin,
          [idToken],
        ),
        returnValue: _i7.Future<_i2.UserModel>.value(_FakeUserModel_0(
          this,
          Invocation.method(
            #googleLogin,
            [idToken],
          ),
        )),
      ) as _i7.Future<_i2.UserModel>);

  @override
  _i7.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.UserModel?> getCachedUser() => (super.noSuchMethod(
        Invocation.method(
          #getCachedUser,
          [],
        ),
        returnValue: _i7.Future<_i2.UserModel?>.value(),
      ) as _i7.Future<_i2.UserModel?>);

  @override
  _i7.Future<_i2.UserModel> getProfile() => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue: _i7.Future<_i2.UserModel>.value(_FakeUserModel_0(
          this,
          Invocation.method(
            #getProfile,
            [],
          ),
        )),
      ) as _i7.Future<_i2.UserModel>);

  @override
  _i7.Future<_i2.UserModel> updateProfile(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [data],
        ),
        returnValue: _i7.Future<_i2.UserModel>.value(_FakeUserModel_0(
          this,
          Invocation.method(
            #updateProfile,
            [data],
          ),
        )),
      ) as _i7.Future<_i2.UserModel>);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i8.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_1(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i3.Dio);

  @override
  _i4.FlutterSecureStorage get secureStorage => (super.noSuchMethod(
        Invocation.getter(#secureStorage),
        returnValue: _FakeFlutterSecureStorage_2(
          this,
          Invocation.getter(#secureStorage),
        ),
      ) as _i4.FlutterSecureStorage);
}

/// A class which mocks [ChatRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRemoteDataSource extends _i1.Mock
    implements _i9.ChatRemoteDataSource {
  MockChatRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<_i5.MessageModel> get messageStream => (super.noSuchMethod(
        Invocation.getter(#messageStream),
        returnValue: _i7.Stream<_i5.MessageModel>.empty(),
      ) as _i7.Stream<_i5.MessageModel>);

  @override
  _i7.Stream<String> get messageDeletedStream => (super.noSuchMethod(
        Invocation.getter(#messageDeletedStream),
        returnValue: _i7.Stream<String>.empty(),
      ) as _i7.Stream<String>);

  @override
  _i7.Stream<dynamic> get notificationStream => (super.noSuchMethod(
        Invocation.getter(#notificationStream),
        returnValue: _i7.Stream<dynamic>.empty(),
      ) as _i7.Stream<dynamic>);

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  _i7.Stream<void> get chatClearedStream => (super.noSuchMethod(
        Invocation.getter(#chatClearedStream),
        returnValue: _i7.Stream<void>.empty(),
      ) as _i7.Stream<void>);

  @override
  _i7.Stream<dynamic> get appointmentSyncStream => (super.noSuchMethod(
        Invocation.getter(#appointmentSyncStream),
        returnValue: _i7.Stream<dynamic>.empty(),
      ) as _i7.Stream<dynamic>);

  @override
  _i7.Stream<dynamic> get notificationSyncStream => (super.noSuchMethod(
        Invocation.getter(#notificationSyncStream),
        returnValue: _i7.Stream<dynamic>.empty(),
      ) as _i7.Stream<dynamic>);

  @override
  _i7.Stream<dynamic> get doctorSyncStream => (super.noSuchMethod(
        Invocation.getter(#doctorSyncStream),
        returnValue: _i7.Stream<dynamic>.empty(),
      ) as _i7.Stream<dynamic>);

  @override
  _i7.Stream<dynamic> get scheduleSyncStream => (super.noSuchMethod(
        Invocation.getter(#scheduleSyncStream),
        returnValue: _i7.Stream<dynamic>.empty(),
      ) as _i7.Stream<dynamic>);

  @override
  _i7.Stream<dynamic> get reviewSyncStream => (super.noSuchMethod(
        Invocation.getter(#reviewSyncStream),
        returnValue: _i7.Stream<dynamic>.empty(),
      ) as _i7.Stream<dynamic>);

  @override
  _i7.Stream<Map<String, dynamic>> get incomingCallStream =>
      (super.noSuchMethod(
        Invocation.getter(#incomingCallStream),
        returnValue: _i7.Stream<Map<String, dynamic>>.empty(),
      ) as _i7.Stream<Map<String, dynamic>>);

  @override
  _i7.Stream<dynamic> get callAcceptedStream => (super.noSuchMethod(
        Invocation.getter(#callAcceptedStream),
        returnValue: _i7.Stream<dynamic>.empty(),
      ) as _i7.Stream<dynamic>);

  @override
  _i7.Stream<dynamic> get iceCandidateStream => (super.noSuchMethod(
        Invocation.getter(#iceCandidateStream),
        returnValue: _i7.Stream<dynamic>.empty(),
      ) as _i7.Stream<dynamic>);

  @override
  _i7.Stream<String> get callEndedStream => (super.noSuchMethod(
        Invocation.getter(#callEndedStream),
        returnValue: _i7.Stream<String>.empty(),
      ) as _i7.Stream<String>);

  @override
  _i7.Stream<String> get typingStream => (super.noSuchMethod(
        Invocation.getter(#typingStream),
        returnValue: _i7.Stream<String>.empty(),
      ) as _i7.Stream<String>);

  @override
  _i7.Stream<String> get stopTypingStream => (super.noSuchMethod(
        Invocation.getter(#stopTypingStream),
        returnValue: _i7.Stream<String>.empty(),
      ) as _i7.Stream<String>);

  @override
  _i7.Future<List<_i10.ChatContact>> getContacts() => (super.noSuchMethod(
        Invocation.method(
          #getContacts,
          [],
        ),
        returnValue:
            _i7.Future<List<_i10.ChatContact>>.value(<_i10.ChatContact>[]),
      ) as _i7.Future<List<_i10.ChatContact>>);

  @override
  _i7.Future<List<_i5.MessageModel>> getMessages(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [userId],
        ),
        returnValue:
            _i7.Future<List<_i5.MessageModel>>.value(<_i5.MessageModel>[]),
      ) as _i7.Future<List<_i5.MessageModel>>);

  @override
  _i7.Future<void> markAsRead(String? senderId) => (super.noSuchMethod(
        Invocation.method(
          #markAsRead,
          [senderId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void connectSocket() => super.noSuchMethod(
        Invocation.method(
          #connectSocket,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void disconnectSocket() => super.noSuchMethod(
        Invocation.method(
          #disconnectSocket,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emitSendMessage(
    String? receiverId,
    String? content,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #emitSendMessage,
          [
            receiverId,
            content,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emitDeleteMessage({
    required String? messageId,
    required String? receiverId,
    required bool? forEveryone,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #emitDeleteMessage,
          [],
          {
            #messageId: messageId,
            #receiverId: receiverId,
            #forEveryone: forEveryone,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emitClearChat({
    required String? receiverId,
    required bool? forEveryone,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #emitClearChat,
          [],
          {
            #receiverId: receiverId,
            #forEveryone: forEveryone,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i5.MessageModel> uploadFile({
    required String? filePath,
    required String? receiverId,
    required String? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [],
          {
            #filePath: filePath,
            #receiverId: receiverId,
            #type: type,
          },
        ),
        returnValue: _i7.Future<_i5.MessageModel>.value(_FakeMessageModel_3(
          this,
          Invocation.method(
            #uploadFile,
            [],
            {
              #filePath: filePath,
              #receiverId: receiverId,
              #type: type,
            },
          ),
        )),
      ) as _i7.Future<_i5.MessageModel>);

  @override
  void emitCallUser({
    required String? userToCall,
    required dynamic signalData,
    required String? from,
    required String? name,
    required String? callType,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #emitCallUser,
          [],
          {
            #userToCall: userToCall,
            #signalData: signalData,
            #from: from,
            #name: name,
            #callType: callType,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emitAnswerCall({
    required String? to,
    required dynamic signal,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #emitAnswerCall,
          [],
          {
            #to: to,
            #signal: signal,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emitIceCandidate({
    required String? to,
    required dynamic candidate,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #emitIceCandidate,
          [],
          {
            #to: to,
            #candidate: candidate,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emitEndCall(String? to) => super.noSuchMethod(
        Invocation.method(
          #emitEndCall,
          [to],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Stream<void> recordSyncStream() => (super.noSuchMethod(
        Invocation.method(
          #recordSyncStream,
          [],
        ),
        returnValue: _i7.Stream<void>.empty(),
      ) as _i7.Stream<void>);

  @override
  _i7.Stream<void> prescriptionSyncStream() => (super.noSuchMethod(
        Invocation.method(
          #prescriptionSyncStream,
          [],
        ),
        returnValue: _i7.Stream<void>.empty(),
      ) as _i7.Stream<void>);

  @override
  void emitTyping(String? recipientId) => super.noSuchMethod(
        Invocation.method(
          #emitTyping,
          [recipientId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emitStopTyping(String? recipientId) => super.noSuchMethod(
        Invocation.method(
          #emitStopTyping,
          [recipientId],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [BiometricService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBiometricService extends _i1.Mock implements _i11.BiometricService {
  MockBiometricService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<bool> isBiometricAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isBiometricAvailable,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<List<_i12.BiometricType>> getAvailableBiometrics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableBiometrics,
          [],
        ),
        returnValue:
            _i7.Future<List<_i12.BiometricType>>.value(<_i12.BiometricType>[]),
      ) as _i7.Future<List<_i12.BiometricType>>);

  @override
  _i7.Future<bool> authenticate() => (super.noSuchMethod(
        Invocation.method(
          #authenticate,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i4.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.IOSOptions get iOptions => (super.noSuchMethod(
        Invocation.getter(#iOptions),
        returnValue: _FakeIOSOptions_4(
          this,
          Invocation.getter(#iOptions),
        ),
      ) as _i4.IOSOptions);

  @override
  _i4.AndroidOptions get aOptions => (super.noSuchMethod(
        Invocation.getter(#aOptions),
        returnValue: _FakeAndroidOptions_5(
          this,
          Invocation.getter(#aOptions),
        ),
      ) as _i4.AndroidOptions);

  @override
  _i4.LinuxOptions get lOptions => (super.noSuchMethod(
        Invocation.getter(#lOptions),
        returnValue: _FakeLinuxOptions_6(
          this,
          Invocation.getter(#lOptions),
        ),
      ) as _i4.LinuxOptions);

  @override
  _i4.WindowsOptions get wOptions => (super.noSuchMethod(
        Invocation.getter(#wOptions),
        returnValue: _FakeWindowsOptions_7(
          this,
          Invocation.getter(#wOptions),
        ),
      ) as _i4.WindowsOptions);

  @override
  _i4.WebOptions get webOptions => (super.noSuchMethod(
        Invocation.getter(#webOptions),
        returnValue: _FakeWebOptions_8(
          this,
          Invocation.getter(#webOptions),
        ),
      ) as _i4.WebOptions);

  @override
  _i4.MacOsOptions get mOptions => (super.noSuchMethod(
        Invocation.getter(#mOptions),
        returnValue: _FakeMacOsOptions_9(
          this,
          Invocation.getter(#mOptions),
        ),
      ) as _i4.MacOsOptions);

  @override
  void registerListener({
    required String? key,
    required _i13.ValueChanged<String?>? listener,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerListener,
          [],
          {
            #key: key,
            #listener: listener,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterListener({
    required String? key,
    required _i13.ValueChanged<String?>? listener,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #unregisterListener,
          [],
          {
            #key: key,
            #listener: listener,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(
          #unregisterAllListenersForKey,
          [],
          {#key: key},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
        Invocation.method(
          #unregisterAllListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> write({
    required String? key,
    required String? value,
    _i4.IOSOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.MacOsOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [],
          {
            #key: key,
            #value: value,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String?> read({
    required String? key,
    _i4.IOSOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.MacOsOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<bool> containsKey({
    required String? key,
    _i4.IOSOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.MacOsOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> delete({
    required String? key,
    _i4.IOSOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.MacOsOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<Map<String, String>> readAll({
    _i4.IOSOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.MacOsOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readAll,
          [],
          {
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i7.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i7.Future<Map<String, String>>);

  @override
  _i7.Future<void> deleteAll({
    _i4.IOSOptions? iOptions,
    _i4.AndroidOptions? aOptions,
    _i4.LinuxOptions? lOptions,
    _i4.WebOptions? webOptions,
    _i4.MacOsOptions? mOptions,
    _i4.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
          {
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool?> isCupertinoProtectedDataAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isCupertinoProtectedDataAvailable,
          [],
        ),
        returnValue: _i7.Future<bool?>.value(),
      ) as _i7.Future<bool?>);
}
