// Mocks generated by Mockito 5.4.4 from annotations
// in doctoroncall/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:dio/dio.dart' as _i2;
import 'package:doctoroncall/core/network/api_client.dart' as _i5;
import 'package:doctoroncall/features/appointments/data/datasources/appointment_local_data_source.dart'
    as _i25;
import 'package:doctoroncall/features/appointments/data/datasources/appointment_remote_data_source.dart'
    as _i23;
import 'package:doctoroncall/features/appointments/data/models/appointment_model.dart'
    as _i24;
import 'package:doctoroncall/features/appointments/domain/entities/appointment.dart'
    as _i22;
import 'package:doctoroncall/features/appointments/domain/repositories/appointment_repository.dart'
    as _i21;
import 'package:doctoroncall/features/auth/data/datasources/auth_remote_data_source.dart'
    as _i13;
import 'package:doctoroncall/features/auth/data/models/user_model.dart' as _i4;
import 'package:doctoroncall/features/auth/domain/repositories/auth_repository.dart'
    as _i12;
import 'package:doctoroncall/features/doctors/data/datasources/doctor_local_data_source.dart'
    as _i20;
import 'package:doctoroncall/features/doctors/data/datasources/doctor_remote_data_source.dart'
    as _i17;
import 'package:doctoroncall/features/doctors/data/models/doctor_model.dart'
    as _i18;
import 'package:doctoroncall/features/doctors/data/models/schedule_model.dart'
    as _i19;
import 'package:doctoroncall/features/doctors/domain/entities/doctor.dart'
    as _i15;
import 'package:doctoroncall/features/doctors/domain/entities/schedule.dart'
    as _i16;
import 'package:doctoroncall/features/doctors/domain/repositories/doctor_repository.dart'
    as _i14;
import 'package:doctoroncall/features/messages/data/datasources/chat_remote_data_source.dart'
    as _i32;
import 'package:doctoroncall/features/messages/data/models/chat_contact_model.dart'
    as _i31;
import 'package:doctoroncall/features/messages/data/models/message_model.dart'
    as _i7;
import 'package:doctoroncall/features/messages/domain/entities/message.dart'
    as _i6;
import 'package:doctoroncall/features/messages/domain/repositories/chat_repository.dart'
    as _i30;
import 'package:doctoroncall/features/notifications/data/datasources/notification_local_data_source.dart'
    as _i28;
import 'package:doctoroncall/features/notifications/data/datasources/notification_remote_data_source.dart'
    as _i27;
import 'package:doctoroncall/features/notifications/data/models/notification_model.dart'
    as _i29;
import 'package:doctoroncall/features/notifications/domain/repositories/notification_repository.dart'
    as _i26;
import 'package:flutter/foundation.dart' as _i8;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i3;
import 'package:hive_flutter/hive_flutter.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlutterSecureStorage_1 extends _i1.SmartFake
    implements _i3.FlutterSecureStorage {
  _FakeFlutterSecureStorage_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIOSOptions_2 extends _i1.SmartFake implements _i3.IOSOptions {
  _FakeIOSOptions_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAndroidOptions_3 extends _i1.SmartFake
    implements _i3.AndroidOptions {
  _FakeAndroidOptions_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLinuxOptions_4 extends _i1.SmartFake implements _i3.LinuxOptions {
  _FakeLinuxOptions_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWindowsOptions_5 extends _i1.SmartFake
    implements _i3.WindowsOptions {
  _FakeWindowsOptions_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWebOptions_6 extends _i1.SmartFake implements _i3.WebOptions {
  _FakeWebOptions_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMacOsOptions_7 extends _i1.SmartFake implements _i3.MacOsOptions {
  _FakeMacOsOptions_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserModel_8 extends _i1.SmartFake implements _i4.UserModel {
  _FakeUserModel_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeApiClient_9 extends _i1.SmartFake implements _i5.ApiClient {
  _FakeApiClient_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMessage_10 extends _i1.SmartFake implements _i6.Message {
  _FakeMessage_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMessageModel_11 extends _i1.SmartFake implements _i7.MessageModel {
  _FakeMessageModel_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseOptions_12 extends _i1.SmartFake implements _i2.BaseOptions {
  _FakeBaseOptions_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpClientAdapter_13 extends _i1.SmartFake
    implements _i2.HttpClientAdapter {
  _FakeHttpClientAdapter_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransformer_14 extends _i1.SmartFake implements _i2.Transformer {
  _FakeTransformer_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInterceptors_15 extends _i1.SmartFake implements _i2.Interceptors {
  _FakeInterceptors_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_16<T1> extends _i1.SmartFake implements _i2.Response<T1> {
  _FakeResponse_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i5.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  _i3.FlutterSecureStorage get secureStorage => (super.noSuchMethod(
        Invocation.getter(#secureStorage),
        returnValue: _FakeFlutterSecureStorage_1(
          this,
          Invocation.getter(#secureStorage),
        ),
      ) as _i3.FlutterSecureStorage);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i3.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.IOSOptions get iOptions => (super.noSuchMethod(
        Invocation.getter(#iOptions),
        returnValue: _FakeIOSOptions_2(
          this,
          Invocation.getter(#iOptions),
        ),
      ) as _i3.IOSOptions);

  @override
  _i3.AndroidOptions get aOptions => (super.noSuchMethod(
        Invocation.getter(#aOptions),
        returnValue: _FakeAndroidOptions_3(
          this,
          Invocation.getter(#aOptions),
        ),
      ) as _i3.AndroidOptions);

  @override
  _i3.LinuxOptions get lOptions => (super.noSuchMethod(
        Invocation.getter(#lOptions),
        returnValue: _FakeLinuxOptions_4(
          this,
          Invocation.getter(#lOptions),
        ),
      ) as _i3.LinuxOptions);

  @override
  _i3.WindowsOptions get wOptions => (super.noSuchMethod(
        Invocation.getter(#wOptions),
        returnValue: _FakeWindowsOptions_5(
          this,
          Invocation.getter(#wOptions),
        ),
      ) as _i3.WindowsOptions);

  @override
  _i3.WebOptions get webOptions => (super.noSuchMethod(
        Invocation.getter(#webOptions),
        returnValue: _FakeWebOptions_6(
          this,
          Invocation.getter(#webOptions),
        ),
      ) as _i3.WebOptions);

  @override
  _i3.MacOsOptions get mOptions => (super.noSuchMethod(
        Invocation.getter(#mOptions),
        returnValue: _FakeMacOsOptions_7(
          this,
          Invocation.getter(#mOptions),
        ),
      ) as _i3.MacOsOptions);

  @override
  void registerListener({
    required String? key,
    required _i8.ValueChanged<String?>? listener,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerListener,
          [],
          {
            #key: key,
            #listener: listener,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterListener({
    required String? key,
    required _i8.ValueChanged<String?>? listener,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #unregisterListener,
          [],
          {
            #key: key,
            #listener: listener,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(
          #unregisterAllListenersForKey,
          [],
          {#key: key},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
        Invocation.method(
          #unregisterAllListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> write({
    required String? key,
    required String? value,
    _i3.IOSOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.MacOsOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [],
          {
            #key: key,
            #value: value,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<String?> read({
    required String? key,
    _i3.IOSOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.MacOsOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i9.Future<String?>.value(),
      ) as _i9.Future<String?>);

  @override
  _i9.Future<bool> containsKey({
    required String? key,
    _i3.IOSOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.MacOsOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<void> delete({
    required String? key,
    _i3.IOSOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.MacOsOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<Map<String, String>> readAll({
    _i3.IOSOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.MacOsOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readAll,
          [],
          {
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i9.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i9.Future<Map<String, String>>);

  @override
  _i9.Future<void> deleteAll({
    _i3.IOSOptions? iOptions,
    _i3.AndroidOptions? aOptions,
    _i3.LinuxOptions? lOptions,
    _i3.WebOptions? webOptions,
    _i3.MacOsOptions? mOptions,
    _i3.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
          {
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<bool?> isCupertinoProtectedDataAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isCupertinoProtectedDataAvailable,
          [],
        ),
        returnValue: _i9.Future<bool?>.value(),
      ) as _i9.Future<bool?>);
}

/// A class which mocks [Box].
///
/// See the documentation for Mockito's code generation for more information.
class MockBox<E> extends _i1.Mock implements _i10.Box<E> {
  MockBox() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Iterable<E> get values => (super.noSuchMethod(
        Invocation.getter(#values),
        returnValue: <E>[],
      ) as Iterable<E>);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  bool get isOpen => (super.noSuchMethod(
        Invocation.getter(#isOpen),
        returnValue: false,
      ) as bool);

  @override
  bool get lazy => (super.noSuchMethod(
        Invocation.getter(#lazy),
        returnValue: false,
      ) as bool);

  @override
  Iterable<dynamic> get keys => (super.noSuchMethod(
        Invocation.getter(#keys),
        returnValue: <dynamic>[],
      ) as Iterable<dynamic>);

  @override
  int get length => (super.noSuchMethod(
        Invocation.getter(#length),
        returnValue: 0,
      ) as int);

  @override
  bool get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: false,
      ) as bool);

  @override
  bool get isNotEmpty => (super.noSuchMethod(
        Invocation.getter(#isNotEmpty),
        returnValue: false,
      ) as bool);

  @override
  Iterable<E> valuesBetween({
    dynamic startKey,
    dynamic endKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #valuesBetween,
          [],
          {
            #startKey: startKey,
            #endKey: endKey,
          },
        ),
        returnValue: <E>[],
      ) as Iterable<E>);

  @override
  E? getAt(int? index) => (super.noSuchMethod(Invocation.method(
        #getAt,
        [index],
      )) as E?);

  @override
  Map<dynamic, E> toMap() => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [],
        ),
        returnValue: <dynamic, E>{},
      ) as Map<dynamic, E>);

  @override
  dynamic keyAt(int? index) => super.noSuchMethod(Invocation.method(
        #keyAt,
        [index],
      ));

  @override
  _i9.Stream<_i10.BoxEvent> watch({dynamic key}) => (super.noSuchMethod(
        Invocation.method(
          #watch,
          [],
          {#key: key},
        ),
        returnValue: _i9.Stream<_i10.BoxEvent>.empty(),
      ) as _i9.Stream<_i10.BoxEvent>);

  @override
  bool containsKey(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i9.Future<void> put(
    dynamic key,
    E? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            value,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> putAt(
    int? index,
    E? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAt,
          [
            index,
            value,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> putAll(Map<dynamic, E>? entries) => (super.noSuchMethod(
        Invocation.method(
          #putAll,
          [entries],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<int> add(E? value) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [value],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<Iterable<int>> addAll(Iterable<E>? values) => (super.noSuchMethod(
        Invocation.method(
          #addAll,
          [values],
        ),
        returnValue: _i9.Future<Iterable<int>>.value(<int>[]),
      ) as _i9.Future<Iterable<int>>);

  @override
  _i9.Future<void> delete(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> deleteAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #deleteAt,
          [index],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> deleteAll(Iterable<dynamic>? keys) => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [keys],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> compact() => (super.noSuchMethod(
        Invocation.method(
          #compact,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<int> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> deleteFromDisk() => (super.noSuchMethod(
        Invocation.method(
          #deleteFromDisk,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> flush() => (super.noSuchMethod(
        Invocation.method(
          #flush,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i12.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<void> signUp(
    _i4.UserModel? user,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [
            user,
            password,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i4.UserModel> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i9.Future<_i4.UserModel>.value(_FakeUserModel_8(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i9.Future<_i4.UserModel>);

  @override
  _i9.Future<_i4.UserModel> googleLogin(String? idToken) => (super.noSuchMethod(
        Invocation.method(
          #googleLogin,
          [idToken],
        ),
        returnValue: _i9.Future<_i4.UserModel>.value(_FakeUserModel_8(
          this,
          Invocation.method(
            #googleLogin,
            [idToken],
          ),
        )),
      ) as _i9.Future<_i4.UserModel>);

  @override
  _i9.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i4.UserModel?> getCachedUser() => (super.noSuchMethod(
        Invocation.method(
          #getCachedUser,
          [],
        ),
        returnValue: _i9.Future<_i4.UserModel?>.value(),
      ) as _i9.Future<_i4.UserModel?>);

  @override
  _i9.Future<_i4.UserModel> getProfile() => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue: _i9.Future<_i4.UserModel>.value(_FakeUserModel_8(
          this,
          Invocation.method(
            #getProfile,
            [],
          ),
        )),
      ) as _i9.Future<_i4.UserModel>);

  @override
  _i9.Future<_i4.UserModel> updateProfile(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [data],
        ),
        returnValue: _i9.Future<_i4.UserModel>.value(_FakeUserModel_8(
          this,
          Invocation.method(
            #updateProfile,
            [data],
          ),
        )),
      ) as _i9.Future<_i4.UserModel>);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i13.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.ApiClient get apiClient => (super.noSuchMethod(
        Invocation.getter(#apiClient),
        returnValue: _FakeApiClient_9(
          this,
          Invocation.getter(#apiClient),
        ),
      ) as _i5.ApiClient);

  @override
  _i9.Future<void> signUp(
    _i4.UserModel? user,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [
            user,
            password,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i4.UserModel> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i9.Future<_i4.UserModel>.value(_FakeUserModel_8(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i9.Future<_i4.UserModel>);

  @override
  _i9.Future<_i4.UserModel> googleLogin(String? idToken) => (super.noSuchMethod(
        Invocation.method(
          #googleLogin,
          [idToken],
        ),
        returnValue: _i9.Future<_i4.UserModel>.value(_FakeUserModel_8(
          this,
          Invocation.method(
            #googleLogin,
            [idToken],
          ),
        )),
      ) as _i9.Future<_i4.UserModel>);

  @override
  _i9.Future<_i4.UserModel?> getCachedUser() => (super.noSuchMethod(
        Invocation.method(
          #getCachedUser,
          [],
        ),
        returnValue: _i9.Future<_i4.UserModel?>.value(),
      ) as _i9.Future<_i4.UserModel?>);

  @override
  _i9.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i4.UserModel> getProfile() => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue: _i9.Future<_i4.UserModel>.value(_FakeUserModel_8(
          this,
          Invocation.method(
            #getProfile,
            [],
          ),
        )),
      ) as _i9.Future<_i4.UserModel>);

  @override
  _i9.Future<_i4.UserModel> updateProfile(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [data],
        ),
        returnValue: _i9.Future<_i4.UserModel>.value(_FakeUserModel_8(
          this,
          Invocation.method(
            #updateProfile,
            [data],
          ),
        )),
      ) as _i9.Future<_i4.UserModel>);
}

/// A class which mocks [DoctorRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDoctorRepository extends _i1.Mock implements _i14.DoctorRepository {
  MockDoctorRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i15.Doctor>> getDoctors() => (super.noSuchMethod(
        Invocation.method(
          #getDoctors,
          [],
        ),
        returnValue: _i9.Future<List<_i15.Doctor>>.value(<_i15.Doctor>[]),
      ) as _i9.Future<List<_i15.Doctor>>);

  @override
  _i9.Future<void> updateSchedule(List<_i16.Schedule>? schedules) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSchedule,
          [schedules],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [DoctorRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDoctorRemoteDataSource extends _i1.Mock
    implements _i17.DoctorRemoteDataSource {
  MockDoctorRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i18.DoctorModel>> getDoctors() => (super.noSuchMethod(
        Invocation.method(
          #getDoctors,
          [],
        ),
        returnValue:
            _i9.Future<List<_i18.DoctorModel>>.value(<_i18.DoctorModel>[]),
      ) as _i9.Future<List<_i18.DoctorModel>>);

  @override
  _i9.Future<void> updateSchedule(List<_i19.ScheduleModel>? schedules) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSchedule,
          [schedules],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [DoctorLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDoctorLocalDataSource extends _i1.Mock
    implements _i20.DoctorLocalDataSource {
  MockDoctorLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i18.DoctorModel> getCachedDoctors() => (super.noSuchMethod(
        Invocation.method(
          #getCachedDoctors,
          [],
        ),
        returnValue: <_i18.DoctorModel>[],
      ) as List<_i18.DoctorModel>);

  @override
  _i9.Future<void> cacheDoctors(List<_i18.DoctorModel>? doctors) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheDoctors,
          [doctors],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [AppointmentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppointmentRepository extends _i1.Mock
    implements _i21.AppointmentRepository {
  MockAppointmentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i22.Appointment>> getAppointments(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAppointments,
          [userId],
        ),
        returnValue:
            _i9.Future<List<_i22.Appointment>>.value(<_i22.Appointment>[]),
      ) as _i9.Future<List<_i22.Appointment>>);

  @override
  _i9.Future<List<_i22.Appointment>> getDoctorAppointments() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDoctorAppointments,
          [],
        ),
        returnValue:
            _i9.Future<List<_i22.Appointment>>.value(<_i22.Appointment>[]),
      ) as _i9.Future<List<_i22.Appointment>>);

  @override
  _i9.Future<void> bookAppointment(_i22.Appointment? appointment) =>
      (super.noSuchMethod(
        Invocation.method(
          #bookAppointment,
          [appointment],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> cancelAppointment(String? appointmentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelAppointment,
          [appointmentId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> updateAppointmentStatus(
    String? appointmentId,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAppointmentStatus,
          [
            appointmentId,
            status,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<Map<String, dynamic>>> getAvailability(
    String? doctorId,
    String? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailability,
          [
            doctorId,
            date,
          ],
        ),
        returnValue: _i9.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i9.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [AppointmentRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppointmentRemoteDataSource extends _i1.Mock
    implements _i23.AppointmentRemoteDataSource {
  MockAppointmentRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i24.AppointmentModel>> getAppointments(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAppointments,
          [userId],
        ),
        returnValue: _i9.Future<List<_i24.AppointmentModel>>.value(
            <_i24.AppointmentModel>[]),
      ) as _i9.Future<List<_i24.AppointmentModel>>);

  @override
  _i9.Future<List<_i24.AppointmentModel>> getDoctorAppointments() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDoctorAppointments,
          [],
        ),
        returnValue: _i9.Future<List<_i24.AppointmentModel>>.value(
            <_i24.AppointmentModel>[]),
      ) as _i9.Future<List<_i24.AppointmentModel>>);

  @override
  _i9.Future<void> bookAppointment(_i24.AppointmentModel? appointment) =>
      (super.noSuchMethod(
        Invocation.method(
          #bookAppointment,
          [appointment],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> cancelAppointment(String? appointmentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelAppointment,
          [appointmentId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> updateAppointmentStatus(
    String? appointmentId,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAppointmentStatus,
          [
            appointmentId,
            status,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<List<Map<String, dynamic>>> getAvailability(
    String? doctorId,
    String? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailability,
          [
            doctorId,
            date,
          ],
        ),
        returnValue: _i9.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i9.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [AppointmentLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppointmentLocalDataSource extends _i1.Mock
    implements _i25.AppointmentLocalDataSource {
  MockAppointmentLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i24.AppointmentModel> getCachedAppointments(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedAppointments,
          [userId],
        ),
        returnValue: <_i24.AppointmentModel>[],
      ) as List<_i24.AppointmentModel>);

  @override
  _i9.Future<void> cacheAppointments(
    String? userId,
    List<_i24.AppointmentModel>? appointments,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheAppointments,
          [
            userId,
            appointments,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  List<_i24.AppointmentModel> getCachedDoctorAppointments() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedDoctorAppointments,
          [],
        ),
        returnValue: <_i24.AppointmentModel>[],
      ) as List<_i24.AppointmentModel>);

  @override
  _i9.Future<void> cacheDoctorAppointments(
          List<_i24.AppointmentModel>? appointments) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheDoctorAppointments,
          [appointments],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [NotificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationRepository extends _i1.Mock
    implements _i26.NotificationRepository {
  MockNotificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<Map<String, dynamic>> getNotifications() => (super.noSuchMethod(
        Invocation.method(
          #getNotifications,
          [],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<void> markAsRead(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markAsRead,
          [id],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> markAllAsRead() => (super.noSuchMethod(
        Invocation.method(
          #markAllAsRead,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [NotificationRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationRemoteDataSource extends _i1.Mock
    implements _i27.NotificationRemoteDataSource {
  MockNotificationRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<Map<String, dynamic>> getNotifications() => (super.noSuchMethod(
        Invocation.method(
          #getNotifications,
          [],
        ),
        returnValue:
            _i9.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i9.Future<Map<String, dynamic>>);

  @override
  _i9.Future<void> markAsRead(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markAsRead,
          [id],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> markAllAsRead() => (super.noSuchMethod(
        Invocation.method(
          #markAllAsRead,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [NotificationLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationLocalDataSource extends _i1.Mock
    implements _i28.NotificationLocalDataSource {
  MockNotificationLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> getCachedNotifications() => (super.noSuchMethod(
        Invocation.method(
          #getCachedNotifications,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i9.Future<void> cacheNotifications(
    List<_i29.NotificationModel>? notifications,
    int? unreadCount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheNotifications,
          [
            notifications,
            unreadCount,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i30.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isSocketConnected => (super.noSuchMethod(
        Invocation.getter(#isSocketConnected),
        returnValue: false,
      ) as bool);

  @override
  _i9.Stream<String> get typingStream => (super.noSuchMethod(
        Invocation.getter(#typingStream),
        returnValue: _i9.Stream<String>.empty(),
      ) as _i9.Stream<String>);

  @override
  _i9.Stream<String> get stopTypingStream => (super.noSuchMethod(
        Invocation.getter(#stopTypingStream),
        returnValue: _i9.Stream<String>.empty(),
      ) as _i9.Stream<String>);

  @override
  _i9.Future<List<_i31.ChatContact>> getContacts() => (super.noSuchMethod(
        Invocation.method(
          #getContacts,
          [],
        ),
        returnValue:
            _i9.Future<List<_i31.ChatContact>>.value(<_i31.ChatContact>[]),
      ) as _i9.Future<List<_i31.ChatContact>>);

  @override
  _i9.Future<List<_i6.Message>> getMessages(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [userId],
        ),
        returnValue: _i9.Future<List<_i6.Message>>.value(<_i6.Message>[]),
      ) as _i9.Future<List<_i6.Message>>);

  @override
  _i9.Future<void> markAsRead(String? senderId) => (super.noSuchMethod(
        Invocation.method(
          #markAsRead,
          [senderId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> sendMessage(_i6.Message? message) => (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [message],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Stream<_i6.Message> receiveMessages() => (super.noSuchMethod(
        Invocation.method(
          #receiveMessages,
          [],
        ),
        returnValue: _i9.Stream<_i6.Message>.empty(),
      ) as _i9.Stream<_i6.Message>);

  @override
  _i9.Stream<String> messageDeletedStream() => (super.noSuchMethod(
        Invocation.method(
          #messageDeletedStream,
          [],
        ),
        returnValue: _i9.Stream<String>.empty(),
      ) as _i9.Stream<String>);

  @override
  _i9.Stream<void> chatClearedStream() => (super.noSuchMethod(
        Invocation.method(
          #chatClearedStream,
          [],
        ),
        returnValue: _i9.Stream<void>.empty(),
      ) as _i9.Stream<void>);

  @override
  void connectSocket() => super.noSuchMethod(
        Invocation.method(
          #connectSocket,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void disconnectSocket() => super.noSuchMethod(
        Invocation.method(
          #disconnectSocket,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deleteMessage({
    required String? messageId,
    required String? receiverId,
    required bool? forEveryone,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #deleteMessage,
          [],
          {
            #messageId: messageId,
            #receiverId: receiverId,
            #forEveryone: forEveryone,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearChat({
    required String? receiverId,
    required bool? forEveryone,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #clearChat,
          [],
          {
            #receiverId: receiverId,
            #forEveryone: forEveryone,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<_i6.Message> uploadFile({
    required String? filePath,
    required String? receiverId,
    required String? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [],
          {
            #filePath: filePath,
            #receiverId: receiverId,
            #type: type,
          },
        ),
        returnValue: _i9.Future<_i6.Message>.value(_FakeMessage_10(
          this,
          Invocation.method(
            #uploadFile,
            [],
            {
              #filePath: filePath,
              #receiverId: receiverId,
              #type: type,
            },
          ),
        )),
      ) as _i9.Future<_i6.Message>);

  @override
  void emitCallUser({
    required String? userToCall,
    required dynamic signalData,
    required String? from,
    required String? name,
    required String? callType,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #emitCallUser,
          [],
          {
            #userToCall: userToCall,
            #signalData: signalData,
            #from: from,
            #name: name,
            #callType: callType,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emitAnswerCall({
    required String? to,
    required dynamic signal,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #emitAnswerCall,
          [],
          {
            #to: to,
            #signal: signal,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emitIceCandidate({
    required String? to,
    required dynamic candidate,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #emitIceCandidate,
          [],
          {
            #to: to,
            #candidate: candidate,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emitEndCall(String? to) => super.noSuchMethod(
        Invocation.method(
          #emitEndCall,
          [to],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Stream<dynamic> appointmentSyncStream() => (super.noSuchMethod(
        Invocation.method(
          #appointmentSyncStream,
          [],
        ),
        returnValue: _i9.Stream<dynamic>.empty(),
      ) as _i9.Stream<dynamic>);

  @override
  _i9.Stream<dynamic> doctorSyncStream() => (super.noSuchMethod(
        Invocation.method(
          #doctorSyncStream,
          [],
        ),
        returnValue: _i9.Stream<dynamic>.empty(),
      ) as _i9.Stream<dynamic>);

  @override
  _i9.Stream<dynamic> scheduleSyncStream() => (super.noSuchMethod(
        Invocation.method(
          #scheduleSyncStream,
          [],
        ),
        returnValue: _i9.Stream<dynamic>.empty(),
      ) as _i9.Stream<dynamic>);

  @override
  _i9.Stream<dynamic> notificationSyncStream() => (super.noSuchMethod(
        Invocation.method(
          #notificationSyncStream,
          [],
        ),
        returnValue: _i9.Stream<dynamic>.empty(),
      ) as _i9.Stream<dynamic>);

  @override
  _i9.Stream<dynamic> reviewSyncStream() => (super.noSuchMethod(
        Invocation.method(
          #reviewSyncStream,
          [],
        ),
        returnValue: _i9.Stream<dynamic>.empty(),
      ) as _i9.Stream<dynamic>);

  @override
  _i9.Stream<dynamic> recordSyncStream() => (super.noSuchMethod(
        Invocation.method(
          #recordSyncStream,
          [],
        ),
        returnValue: _i9.Stream<dynamic>.empty(),
      ) as _i9.Stream<dynamic>);

  @override
  _i9.Stream<dynamic> prescriptionSyncStream() => (super.noSuchMethod(
        Invocation.method(
          #prescriptionSyncStream,
          [],
        ),
        returnValue: _i9.Stream<dynamic>.empty(),
      ) as _i9.Stream<dynamic>);

  @override
  void emitTyping(String? recipientId) => super.noSuchMethod(
        Invocation.method(
          #emitTyping,
          [recipientId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emitStopTyping(String? recipientId) => super.noSuchMethod(
        Invocation.method(
          #emitStopTyping,
          [recipientId],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ChatRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRemoteDataSource extends _i1.Mock
    implements _i32.ChatRemoteDataSource {
  MockChatRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Stream<_i7.MessageModel> get messageStream => (super.noSuchMethod(
        Invocation.getter(#messageStream),
        returnValue: _i9.Stream<_i7.MessageModel>.empty(),
      ) as _i9.Stream<_i7.MessageModel>);

  @override
  _i9.Stream<String> get messageDeletedStream => (super.noSuchMethod(
        Invocation.getter(#messageDeletedStream),
        returnValue: _i9.Stream<String>.empty(),
      ) as _i9.Stream<String>);

  @override
  _i9.Stream<dynamic> get notificationStream => (super.noSuchMethod(
        Invocation.getter(#notificationStream),
        returnValue: _i9.Stream<dynamic>.empty(),
      ) as _i9.Stream<dynamic>);

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  _i9.Stream<void> get chatClearedStream => (super.noSuchMethod(
        Invocation.getter(#chatClearedStream),
        returnValue: _i9.Stream<void>.empty(),
      ) as _i9.Stream<void>);

  @override
  _i9.Stream<dynamic> get appointmentSyncStream => (super.noSuchMethod(
        Invocation.getter(#appointmentSyncStream),
        returnValue: _i9.Stream<dynamic>.empty(),
      ) as _i9.Stream<dynamic>);

  @override
  _i9.Stream<dynamic> get notificationSyncStream => (super.noSuchMethod(
        Invocation.getter(#notificationSyncStream),
        returnValue: _i9.Stream<dynamic>.empty(),
      ) as _i9.Stream<dynamic>);

  @override
  _i9.Stream<dynamic> get doctorSyncStream => (super.noSuchMethod(
        Invocation.getter(#doctorSyncStream),
        returnValue: _i9.Stream<dynamic>.empty(),
      ) as _i9.Stream<dynamic>);

  @override
  _i9.Stream<dynamic> get scheduleSyncStream => (super.noSuchMethod(
        Invocation.getter(#scheduleSyncStream),
        returnValue: _i9.Stream<dynamic>.empty(),
      ) as _i9.Stream<dynamic>);

  @override
  _i9.Stream<dynamic> get reviewSyncStream => (super.noSuchMethod(
        Invocation.getter(#reviewSyncStream),
        returnValue: _i9.Stream<dynamic>.empty(),
      ) as _i9.Stream<dynamic>);

  @override
  _i9.Stream<Map<String, dynamic>> get incomingCallStream =>
      (super.noSuchMethod(
        Invocation.getter(#incomingCallStream),
        returnValue: _i9.Stream<Map<String, dynamic>>.empty(),
      ) as _i9.Stream<Map<String, dynamic>>);

  @override
  _i9.Stream<dynamic> get callAcceptedStream => (super.noSuchMethod(
        Invocation.getter(#callAcceptedStream),
        returnValue: _i9.Stream<dynamic>.empty(),
      ) as _i9.Stream<dynamic>);

  @override
  _i9.Stream<dynamic> get iceCandidateStream => (super.noSuchMethod(
        Invocation.getter(#iceCandidateStream),
        returnValue: _i9.Stream<dynamic>.empty(),
      ) as _i9.Stream<dynamic>);

  @override
  _i9.Stream<String> get callEndedStream => (super.noSuchMethod(
        Invocation.getter(#callEndedStream),
        returnValue: _i9.Stream<String>.empty(),
      ) as _i9.Stream<String>);

  @override
  _i9.Stream<String> get typingStream => (super.noSuchMethod(
        Invocation.getter(#typingStream),
        returnValue: _i9.Stream<String>.empty(),
      ) as _i9.Stream<String>);

  @override
  _i9.Stream<String> get stopTypingStream => (super.noSuchMethod(
        Invocation.getter(#stopTypingStream),
        returnValue: _i9.Stream<String>.empty(),
      ) as _i9.Stream<String>);

  @override
  _i9.Future<List<_i31.ChatContact>> getContacts() => (super.noSuchMethod(
        Invocation.method(
          #getContacts,
          [],
        ),
        returnValue:
            _i9.Future<List<_i31.ChatContact>>.value(<_i31.ChatContact>[]),
      ) as _i9.Future<List<_i31.ChatContact>>);

  @override
  _i9.Future<List<_i7.MessageModel>> getMessages(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [userId],
        ),
        returnValue:
            _i9.Future<List<_i7.MessageModel>>.value(<_i7.MessageModel>[]),
      ) as _i9.Future<List<_i7.MessageModel>>);

  @override
  _i9.Future<void> markAsRead(String? senderId) => (super.noSuchMethod(
        Invocation.method(
          #markAsRead,
          [senderId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void connectSocket() => super.noSuchMethod(
        Invocation.method(
          #connectSocket,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void disconnectSocket() => super.noSuchMethod(
        Invocation.method(
          #disconnectSocket,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emitSendMessage(
    String? receiverId,
    String? content,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #emitSendMessage,
          [
            receiverId,
            content,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emitDeleteMessage({
    required String? messageId,
    required String? receiverId,
    required bool? forEveryone,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #emitDeleteMessage,
          [],
          {
            #messageId: messageId,
            #receiverId: receiverId,
            #forEveryone: forEveryone,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emitClearChat({
    required String? receiverId,
    required bool? forEveryone,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #emitClearChat,
          [],
          {
            #receiverId: receiverId,
            #forEveryone: forEveryone,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<_i7.MessageModel> uploadFile({
    required String? filePath,
    required String? receiverId,
    required String? type,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [],
          {
            #filePath: filePath,
            #receiverId: receiverId,
            #type: type,
          },
        ),
        returnValue: _i9.Future<_i7.MessageModel>.value(_FakeMessageModel_11(
          this,
          Invocation.method(
            #uploadFile,
            [],
            {
              #filePath: filePath,
              #receiverId: receiverId,
              #type: type,
            },
          ),
        )),
      ) as _i9.Future<_i7.MessageModel>);

  @override
  void emitCallUser({
    required String? userToCall,
    required dynamic signalData,
    required String? from,
    required String? name,
    required String? callType,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #emitCallUser,
          [],
          {
            #userToCall: userToCall,
            #signalData: signalData,
            #from: from,
            #name: name,
            #callType: callType,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emitAnswerCall({
    required String? to,
    required dynamic signal,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #emitAnswerCall,
          [],
          {
            #to: to,
            #signal: signal,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emitIceCandidate({
    required String? to,
    required dynamic candidate,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #emitIceCandidate,
          [],
          {
            #to: to,
            #candidate: candidate,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emitEndCall(String? to) => super.noSuchMethod(
        Invocation.method(
          #emitEndCall,
          [to],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Stream<void> recordSyncStream() => (super.noSuchMethod(
        Invocation.method(
          #recordSyncStream,
          [],
        ),
        returnValue: _i9.Stream<void>.empty(),
      ) as _i9.Stream<void>);

  @override
  _i9.Stream<void> prescriptionSyncStream() => (super.noSuchMethod(
        Invocation.method(
          #prescriptionSyncStream,
          [],
        ),
        returnValue: _i9.Stream<void>.empty(),
      ) as _i9.Stream<void>);

  @override
  void emitTyping(String? recipientId) => super.noSuchMethod(
        Invocation.method(
          #emitTyping,
          [recipientId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emitStopTyping(String? recipientId) => super.noSuchMethod(
        Invocation.method(
          #emitStopTyping,
          [recipientId],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i2.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeBaseOptions_12(
          this,
          Invocation.getter(#options),
        ),
      ) as _i2.BaseOptions);

  @override
  set options(_i2.BaseOptions? _options) => super.noSuchMethod(
        Invocation.setter(
          #options,
          _options,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.HttpClientAdapter get httpClientAdapter => (super.noSuchMethod(
        Invocation.getter(#httpClientAdapter),
        returnValue: _FakeHttpClientAdapter_13(
          this,
          Invocation.getter(#httpClientAdapter),
        ),
      ) as _i2.HttpClientAdapter);

  @override
  set httpClientAdapter(_i2.HttpClientAdapter? _httpClientAdapter) =>
      super.noSuchMethod(
        Invocation.setter(
          #httpClientAdapter,
          _httpClientAdapter,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Transformer get transformer => (super.noSuchMethod(
        Invocation.getter(#transformer),
        returnValue: _FakeTransformer_14(
          this,
          Invocation.getter(#transformer),
        ),
      ) as _i2.Transformer);

  @override
  set transformer(_i2.Transformer? _transformer) => super.noSuchMethod(
        Invocation.setter(
          #transformer,
          _transformer,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Interceptors get interceptors => (super.noSuchMethod(
        Invocation.getter(#interceptors),
        returnValue: _FakeInterceptors_15(
          this,
          Invocation.getter(#interceptors),
        ),
      ) as _i2.Interceptors);

  @override
  void close({bool? force = false}) => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {#force: force},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<_i2.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_16<T>(
          this,
          Invocation.method(
            #head,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i9.Future<_i2.Response<T>>);

  @override
  _i9.Future<_i2.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #headUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_16<T>(
          this,
          Invocation.method(
            #headUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i9.Future<_i2.Response<T>>);

  @override
  _i9.Future<_i2.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_16<T>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i2.Response<T>>);

  @override
  _i9.Future<_i2.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_16<T>(
          this,
          Invocation.method(
            #getUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i2.Response<T>>);

  @override
  _i9.Future<_i2.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_16<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i2.Response<T>>);

  @override
  _i9.Future<_i2.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_16<T>(
          this,
          Invocation.method(
            #postUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i2.Response<T>>);

  @override
  _i9.Future<_i2.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_16<T>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i2.Response<T>>);

  @override
  _i9.Future<_i2.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_16<T>(
          this,
          Invocation.method(
            #putUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i2.Response<T>>);

  @override
  _i9.Future<_i2.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_16<T>(
          this,
          Invocation.method(
            #patch,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i2.Response<T>>);

  @override
  _i9.Future<_i2.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patchUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_16<T>(
          this,
          Invocation.method(
            #patchUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i2.Response<T>>);

  @override
  _i9.Future<_i2.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_16<T>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i9.Future<_i2.Response<T>>);

  @override
  _i9.Future<_i2.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_16<T>(
          this,
          Invocation.method(
            #deleteUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i9.Future<_i2.Response<T>>);

  @override
  _i9.Future<_i2.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i2.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = r'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [
            urlPath,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #fileAccessMode: fileAccessMode,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i9.Future<_i2.Response<dynamic>>.value(_FakeResponse_16<dynamic>(
          this,
          Invocation.method(
            #download,
            [
              urlPath,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #fileAccessMode: fileAccessMode,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i9.Future<_i2.Response<dynamic>>);

  @override
  _i9.Future<_i2.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    _i2.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = r'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadUri,
          [
            uri,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #fileAccessMode: fileAccessMode,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i9.Future<_i2.Response<dynamic>>.value(_FakeResponse_16<dynamic>(
          this,
          Invocation.method(
            #downloadUri,
            [
              uri,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #fileAccessMode: fileAccessMode,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i9.Future<_i2.Response<dynamic>>);

  @override
  _i9.Future<_i2.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [url],
          {
            #data: data,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_16<T>(
          this,
          Invocation.method(
            #request,
            [url],
            {
              #data: data,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i2.Response<T>>);

  @override
  _i9.Future<_i2.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i2.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestUri,
          [uri],
          {
            #data: data,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_16<T>(
          this,
          Invocation.method(
            #requestUri,
            [uri],
            {
              #data: data,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i2.Response<T>>);

  @override
  _i9.Future<_i2.Response<T>> fetch<T>(_i2.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [requestOptions],
        ),
        returnValue: _i9.Future<_i2.Response<T>>.value(_FakeResponse_16<T>(
          this,
          Invocation.method(
            #fetch,
            [requestOptions],
          ),
        )),
      ) as _i9.Future<_i2.Response<T>>);

  @override
  _i2.Dio clone({
    _i2.BaseOptions? options,
    _i2.Interceptors? interceptors,
    _i2.HttpClientAdapter? httpClientAdapter,
    _i2.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clone,
          [],
          {
            #options: options,
            #interceptors: interceptors,
            #httpClientAdapter: httpClientAdapter,
            #transformer: transformer,
          },
        ),
        returnValue: _FakeDio_0(
          this,
          Invocation.method(
            #clone,
            [],
            {
              #options: options,
              #interceptors: interceptors,
              #httpClientAdapter: httpClientAdapter,
              #transformer: transformer,
            },
          ),
        ),
      ) as _i2.Dio);
}
